class AddDummyColumnToTables < ActiveRecord::Migration[6.1]
  def change
    add_column:advance_molecular_rheometers, :dummy2, :string
    add_column:atomic_force_microscopes, :dummy2, :string
    add_column:ball_mailings, :dummy2, :string
    add_column:bets, :dummy2, :string
    add_column:cell_imagings, :dummy2, :string
    add_column:electro_chemicals, :dummy2, :string
    add_column:five_axis, :dummy2, :string
    add_column:frictions, :dummy2, :string
    add_column:gaits, :dummy2, :string
    add_column:gas_sensings, :dummy2, :string
    add_column:glove_boxes, :dummy2, :string
    add_column:glows, :dummy2, :string
    add_column:grindings, :dummy2, :string
    add_column:high_temp_vaccums, :dummy2, :string
    add_column:hr_fesem_cs, :dummy2, :string
    add_column:hr_fesem_js, :dummy2, :string
    add_column:hrlcms, :dummy2, :string
    add_column:icp_ms, :dummy2, :string
    add_column:impedance_analies, :dummy2, :string
    add_column:integrated_multi_role_testers, :dummy2, :string
    add_column:ion_chromotographies, :dummy2, :string
    add_column:lasers, :dummy2, :string
    add_column:low_fatigues, :dummy2, :string
    add_column:micro_edms, :dummy2, :string
    add_column:milli_qs, :dummy2, :string
    add_column:multi_impact_testers, :dummy2, :string
    add_column:probe_sonicators, :dummy2, :string
    add_column:raman_microscopes, :dummy2, :string
    add_column:scratch_indentations, :dummy2, :string
    add_column:spark_os, :dummy2, :string
    add_column:spectro_radio_meters, :dummy2, :string
    add_column:tga_fttrs, :dummy2, :string
    add_column:three_d_non_contacts, :dummy2, :string
    add_column:three_d_scanners, :dummy2, :string
    add_column:tribometers, :dummy2, :string
    add_column:ultra_centrifuges, :dummy2, :string
    add_column:uv_vis_nirs, :dummy2, :string
    add_column:zeta_potential_sizes, :dummy2, :string
    add_column:xrds, :dummy2, :string

    add_column:advance_molecular_rheometers, :dummy3, :string
    add_column:atomic_force_microscopes, :dummy3, :string
    add_column:ball_mailings, :dummy3, :string
    add_column:bets, :dummy3, :string
    add_column:cell_imagings, :dummy3, :string
    add_column:electro_chemicals, :dummy3, :string
    add_column:five_axis, :dummy3, :string
    add_column:frictions, :dummy3, :string
    add_column:gaits, :dummy3, :string
    add_column:gas_sensings, :dummy3, :string
    add_column:glove_boxes, :dummy3, :string
    add_column:glows, :dummy3, :string
    add_column:grindings, :dummy3, :string
    add_column:high_temp_vaccums, :dummy3, :string
    add_column:hr_fesem_cs, :dummy3, :string
    add_column:hr_fesem_js, :dummy3, :string
    add_column:hrlcms, :dummy3, :string
    add_column:icp_ms, :dummy3, :string
    add_column:impedance_analies, :dummy3, :string
    add_column:integrated_multi_role_testers, :dummy3, :string
    add_column:ion_chromotographies, :dummy3, :string
    add_column:lasers, :dummy3, :string
    add_column:low_fatigues, :dummy3, :string
    add_column:micro_edms, :dummy3, :string
    add_column:milli_qs, :dummy3, :string
    add_column:multi_impact_testers, :dummy3, :string
    add_column:probe_sonicators, :dummy3, :string
    add_column:raman_microscopes, :dummy3, :string
    add_column:scratch_indentations, :dummy3, :string
    add_column:spark_os, :dummy3, :string
    add_column:spectro_radio_meters, :dummy3, :string
    add_column:tga_fttrs, :dummy3, :string
    add_column:three_d_non_contacts, :dummy3, :string
    add_column:three_d_scanners, :dummy3, :string
    add_column:tribometers, :dummy3, :string
    add_column:ultra_centrifuges, :dummy3, :string
    add_column:uv_vis_nirs, :dummy3, :string
    add_column:zeta_potential_sizes, :dummy3, :string
    add_column:xrds, :dummy3, :string

  end
end
