class AddColumnHrFesem < ActiveRecord::Migration[6.1]
  def change
    add_column :hr_fesem_cs,:slottype,:string
    add_column :hr_fesem_cs,:expresssample,:integer
    add_column :hr_fesem_js,:slottype,:string
    add_column :hr_fesem_js,:expresssample,:integer
    add_column :three_d_non_contacts,:slottype,:string
    add_column :three_d_non_contacts,:expresssample,:integer
    add_column :raman_microscopes,:slottype,:string
    add_column :raman_microscopes,:expresssample,:integer
    add_column :tga_fttrs,:slottype,:string
    add_column :tga_fttrs,:expresssample,:integer
    add_column :bets,:slottype,:string
    add_column :bets,:expresssample,:integer
    add_column :hrlcms,:slottype,:string
    add_column :hrlcms,:expresssample,:integer
    add_column :uv_vis_nirs,:slottype,:string
    add_column :uv_vis_nirs,:expresssample,:integer
    add_column :lasers,:slottype,:string
    add_column :lasers,:expresssample,:integer
    add_column :cell_imagings,:slottype,:string
    add_column :cell_imagings,:expresssample,:integer
    add_column :atomic_force_microscopes,:slottype,:string
    add_column :atomic_force_microscopes,:expresssample,:integer
    add_column :ft_nms,:slottype,:string
    add_column :ft_nms,:expresssample,:integer
    add_column :icp_ms,:slottype,:string
    add_column :icp_ms,:expresssample,:integer
    add_column :advance_molecular_rheometers,:slottype,:string
    add_column :advance_molecular_rheometers,:expresssample,:integer
    add_column :ion_chromotographies,:slottype,:string
    add_column :ion_chromotographies,:expresssample,:integer
    add_column :integrated_multi_role_testers,:slottype,:string
    add_column :integrated_multi_role_testers,:expresssample,:integer
    add_column :scratch_indentations,:slottype,:string
    add_column :scratch_indentations,:expresssample,:integer
    add_column :zeta_potential_sizes,:slottype,:string
    add_column :zeta_potential_sizes,:expresssample,:integer
    add_column :high_temp_vaccums,:slottype,:string
    add_column :high_temp_vaccums,:expresssample,:integer
    add_column :impedance_analies,:slottype,:string
    add_column :impedance_analies,:expresssample,:integer
    add_column :tribometers,:slottype,:string
    add_column :tribometers,:expresssample,:integer
    add_column :three_d_scanners,:slottype,:string
    add_column :three_d_scanners,:expresssample,:integer
  end
end
